apiVersion: v1
kind: Pod
metadata:
  name: startup-demo
spec:
  containers:
  - name: startup-container
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "Starting...";
        sleep 20;
        echo "Started" > /tmp/started;
        sleep 600

    startupProbe:
      exec:
        command:
        - cat
        - /tmp/started
      periodSeconds: 5
      failureThreshold: 12

    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/started
      periodSeconds: 5